export const mockJobs = [
  {
    id: '1',
    clientId: 'client-1',
    title: 'Build Modern E-Commerce Website',
    description: 'Need a full-stack e-commerce platform with payment integration, product management, and user authentication.',
    category: 'Development & IT',
    budget: 150000,
    duration: '4 weeks',
    level: 'intermediate',
    skills: ['React', 'Node.js', 'MongoDB', 'Stripe'],
    proposals: [],
    status: 'open',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    clientId: 'client-2',
    title: 'Mobile App UI/UX Design',
    description: 'Design beautiful and intuitive UI/UX for iOS and Android mobile app in Figma.',
    category: 'Design & Creative',
    budget: 80000,
    duration: '2 weeks',
    level: 'beginner',
    skills: ['Figma', 'UI Design', 'UX Design', 'Mobile Design'],
    proposals: [],
    status: 'open',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    clientId: 'client-3',
    title: 'AI Chatbot Development',
    description: 'Develop an AI-powered chatbot using GPT-4 API for customer support automation.',
    category: 'AI Services',
    budget: 200000,
    duration: '3 weeks',
    level: 'expert',
    skills: ['Python', 'OpenAI API', 'NLP', 'Flask'],
    proposals: [],
    status: 'open',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockFreelancers = [
  {
    id: 'freelancer-1',
    email: 'dev@example.com',
    name: 'Rahul Kumar',
    avatar: undefined,
    role: 'freelancer',
    phone: '+91 98765 43210',
    bio: 'Full-stack developer with 5+ years experience in React and Node.js',
    location: 'India',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    skills: ['React', 'Node.js', 'MongoDB', 'TypeScript', 'AWS'],
    hourlyRate: 800,
    totalEarnings: 450000,
    completedProjects: 23,
    rating: 4.8,
    reviews: [],
  },
  {
    id: 'freelancer-2',
    email: 'designer@example.com',
    name: 'Priya Singh',
    avatar: undefined,
    role: 'freelancer',
    phone: '+91 98765 43211',
    bio: 'UI/UX Designer specializing in mobile apps and SaaS platforms',
    location: 'India',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    skills: ['Figma', 'UI Design', 'UX Design', 'Prototyping', 'Illustrator'],
    hourlyRate: 600,
    totalEarnings: 320000,
    completedProjects: 18,
    rating: 4.9,
    reviews: [],
  },
];
